name: mac

permissions:
  contents: read

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  mac-build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v6
      - name: Setup .NET
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: 10.0.x
      - name: Restore dependencies
        run: dotnet restore MajorsilenceReporting-Linux-GtkViewer.slnx
      - name: Build GtkViewer
        run: dotnet build -c Release MajorsilenceReporting-Linux-GtkViewer.slnx
      - name: Build MajorsilenceReporting
        run: dotnet build -c Release -p:EnableWindowsTargeting=true MajorsilenceReporting.slnx
      - name: Test
        run: dotnet test -c Release -p:EnableWindowsTargeting=true MajorsilenceReporting.slnx --filter "TestCategory!=Containers" --verbosity normal --collect:"XPlat Code Coverage" --logger:"trx"
      - name: Test Report
        uses: dorny/test-reporter@v2
        if: success() || failure() # run this step even if previous step failed
        with:
          name: unit tests
          path: "**/TestResults/*.trx"
          reporter: dotnet-trx
      - name: Build AOT macOS
        id: aot_build
        shell: pwsh
        run: ./build-release-aot-osx.ps1
      - name: Archive AOT artifacts
        uses: actions/upload-artifact@v6
        with:
          name: majorsilence-reporting-aot-osx-${{ steps.aot_build.outputs.version }}
          path: Release-Builds/build-output/*.zip
          retention-days: 1
